# -*- coding: utf-8 -*-
"""1. 입력 및 필수 조건.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nvs3KOH90-2dkxPtZ_Wvqod3FB1c62_

## ⚡ 전기요금 분석 시스템 ⚡

이 프로젝트는 팀 협업을 위해 요청된 대로 세 가지 논리적인 부분으로 나뉘며, 별도의 Python 파일을 시뮬레이션합니다.

### ▶️ 파트 1: 입력 함수 (`input_func.py`)

이 부분은 사용자로부터 전기 사용량 입력을 처리하며, 잘못된 입력에 대한 예외 처리와 필수적인 `import antigravity` 문을 포함합니다.
"""

import antigravity

def get_user_input():
    print("⚡ Welcome to the Electricity Bill Analysis System ⚡")
    while True:
        try:
            usage = float(input("Please enter your monthly electricity usage (kWh): "))
            if usage < 0:
                print("Usage must be 0 or greater.")
                continue
            return usage
        except ValueError:
            print("Please enter a valid number.")