# -*- coding: utf-8 -*-
"""2. 요금 계산.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nvs3KOH90-2dkxPtZ_Wvqod3FB1c62_

## ⚡ 전기요금 분석 시스템 ⚡

이 프로젝트는 팀 협업을 위해 요청된 대로 세 가지 논리적인 부분으로 나뉘며, 별도의 Python 파일을 시뮬레이션합니다.

### ▶️ 파트 2: 요금 계산 로직 (`calc_func.py`)

이 섹션은 전기 요금에 대한 상수를 정의하고 `calculate_bill` 함수를 구현하여, 사용량 단계별로 총 전기 요금을 결정하고 부가세 및 전력산업기반기금을 추가합니다.
"""

import math

# 전기요금 상수 및 요율 (2024년 한국전력공사 주택용 저압 기준)
# 기본 요금
BASE_RATE_TIER1 = 910   # 200kWh 이하
BASE_RATE_TIER2 = 1600  # 201kWh ~ 400kWh
BASE_RATE_TIER3 = 7300  # 400kWh 초과

# 전력량 요금 (원/kWh)
UNIT_RATE_TIER1 = 120.0  # 첫 200kWh
UNIT_RATE_TIER2 = 214.6  # 다음 200kWh (201~400kWh)
UNIT_RATE_TIER3 = 307.3  # 400kWh 초과

# 기타 요금
VAT_RATE = 0.10   # 부가가치세 10%
FUND_RATE = 0.037 # 전력산업기반기금 3.7%

def calculate_bill(usage):
    # 기본요금 계산
    if usage <= 200:
        base_charge = BASE_RATE_TIER1
    elif usage <= 400:
        base_charge = BASE_RATE_TIER2
    else:
        base_charge = BASE_RATE_TIER3

    # 전력량 요금 계산 (누진)
    energy_charge = 0
    if usage > 0:
        if usage <= 200:
            energy_charge = usage * UNIT_RATE_TIER1
        elif usage <= 400:
            energy_charge = (200 * UNIT_RATE_TIER1) + ((usage - 200) * UNIT_RATE_TIER2)
        else:
            energy_charge = (200 * UNIT_RATE_TIER1) + (200 * UNIT_RATE_TIER2) + ((usage - 400) * UNIT_RATE_TIER3)

    # 총 전기요금 (기본 + 전력량)
    total_electricity_charge = base_charge + energy_charge

    # 부가가치세 (총 전기요금의 10%, 10원 미만 절사)
    vat = math.floor(total_electricity_charge * VAT_RATE / 10) * 10

    # 전력산업기반기금 (총 전기요금의 3.7%, 10원 미만 절사)
    fund = math.floor(total_electricity_charge * FUND_RATE / 10) * 10

    # 최종 청구 금액
    final_bill = total_electricity_charge + vat + fund

    return int(final_bill) # 정수로 반환