# -*- coding: utf-8 -*-
"""3. 결과 출력 및 메인 실행.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11nvs3KOH90-2dkxPtZ_Wvqod3FB1c62_

## ⚡ 전기요금 분석 시스템 ⚡

이 프로젝트는 팀 협업을 위해 요청된 대로 세 가지 논리적인 부분으로 나뉘며, 별도의 Python 파일을 시뮬레이션합니다.

### ▶️ 파트 3: 결과 출력, 시각화 및 메인 실행 (`output_func.py` 역할을 하는 `main.py`)

이 부분에는 계산된 요금을 영수증 형식으로 표시하는 함수, 예상 가전제품 소비량을 파이 차트로 시각화하는 함수, 그리고 전체 시스템을 조정하는 메인 함수가 포함되어 있습니다.
"""

import matplotlib.pyplot as plt

# input_func 및 calc_func가 동일한 디렉토리에 있거나 경로를 통해 접근 가능하다고 가정합니다.
# Colab 환경에서는 이들을 직접 정의하거나 미리 실행되었다고 가정합니다.
# 실제 프로젝트에서는 다음과 같이 임포트됩니다:
# from input_func import get_user_input
# from calc_func import calculate_bill

# Colab 실행을 위한 플레이스홀더 정의. 실제 다중 파일 설정에서는,
# 이들은 제거되고 함수들이 임포트됩니다.

# --- Colab용 플레이스홀더 시작 --- #
import antigravity

def get_user_input():
    print("⚡ Welcome to the Electricity Bill Analysis System ⚡")
    while True:
        try:
            usage = float(input("Please enter your monthly electricity usage (kWh): "))
            if usage < 0:
                print("Usage must be 0 or greater.")
                continue
            return usage
        except ValueError:
            print("Please enter a valid number.")

import math

BASE_RATE_TIER1 = 910
BASE_RATE_TIER2 = 1600
BASE_RATE_TIER3 = 7300
UNIT_RATE_TIER1 = 120.0
UNIT_RATE_TIER2 = 214.6
UNIT_RATE_TIER3 = 307.3
VAT_RATE = 0.10
FUND_RATE = 0.037

def calculate_bill(usage):
    if usage <= 200:
        base_charge = BASE_RATE_TIER1
    elif usage <= 400:
        base_charge = BASE_RATE_TIER2
    else:
        base_charge = BASE_RATE_TIER3

    energy_charge = 0
    if usage > 0:
        if usage <= 200:
            energy_charge = usage * UNIT_RATE_TIER1
        elif usage <= 400:
            energy_charge = (200 * UNIT_RATE_TIER1) + ((usage - 200) * UNIT_RATE_TIER2)
        else:
            energy_charge = (200 * UNIT_RATE_TIER1) + (200 * UNIT_RATE_TIER2) + ((usage - 400) * UNIT_RATE_TIER3)

    total_electricity_charge = base_charge + energy_charge

    vat = math.floor(total_electricity_charge * VAT_RATE / 10) * 10
    fund = math.floor(total_electricity_charge * FUND_RATE / 10) * 10

    final_bill = total_electricity_charge + vat + fund

    return int(final_bill)
# --- Colab용 플레이스홀더 끝 --- #

def print_result(usage, bill):
    print("\n--- Electricity Bill Receipt ---")
    print(f"Monthly Electricity Usage: {usage:.1f} kWh")
    print(f"Total Bill: {bill:,} KRW")
    print("--------------------------------")

    # 누진세 구간 메시지
    if usage <= 200:
        print("Tier 1: Efficient usage. Keep up the good work!")
    elif usage <= 400:
        print("Tier 2: Moderate usage. Consider reducing consumption to save more.")
    else:
        print("Tier 3: High usage. You are in the highest tier, significant savings possible with reduced consumption.")
    print("--------------------------------")

def draw_pie_chart(usage):
    # 가전제품 전력 소비량의 고정 비율
    labels = ['HVAC', 'Refrigerator', 'Lighting & TV', 'Others']
    sizes = [40, 25, 20, 15] # 비율
    colors = ['#ff9999','#66b3ff','#99ff99','#ffcc99']
    explode = (0.05, 0, 0, 0) # 첫 번째 조각 (HVAC) 강조

    fig1, ax1 = plt.subplots(figsize=(8, 8))
    ax1.pie(sizes, explode=explode, labels=labels, colors=colors, autopct='%1.1f%%',
            shadow=True, startangle=90, textprops={'fontsize': 12, 'color': 'black'})
    ax1.axis('equal')  # 동일한 종횡비는 파이가 원으로 그려지도록 보장합니다.

    plt.title('Estimated Appliance Power Consumption Distribution', fontsize=14, color='black')
    plt.show()

def main():
    usage = get_user_input()
    bill = calculate_bill(usage)
    print_result(usage, bill)
    draw_pie_chart(usage) # 컨텍스트에 필요하면 사용량을 전달하지만, 비율은 고정되어 있습니다.

if __name__ == "__main__":
    main()